### 1. Import the numpy package under the name np.

In [1]:
import numpy as np

### 2. Print the numpy version and the configuration.


In [13]:
print(np.show_config())
print(np.version.full_version)

mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/anoj/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/anoj/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/anoj/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/anoj/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/anoj/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/anoj/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/anoj/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/anoj/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/anoj/anaconda3/lib']
    define_macros = [('S

###  3. Create a null vector of size 10.

Note: A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used. 

In [2]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4. How to find the memory size of any array

There are two ways we can find memory size of an array. One is direct method by using 'nbytes' function. Another one is by finding multiplying the size of an array with memory consumed by each individual element.  To find size of an array  we use 'size' function and memory consumed by each individual array we use 'itemsize' function. Lets us try to find the memory of above null_vector array.

In [10]:
# Method I

print(null_vector.nbytes)                       # Finds the total memory size of an array.
 

# Method II

array_size = null_vector.size                   # Finds the size of an array.

unit_memory_size = null_vector.itemsize         # Finds the memory size of each individual unit.

print(array_size*unit_memory_size)


80
80


### 5. How to get the documentation of the numpy add function from the command line?

There is a 'info' function in numpy that prints the documentation for any numpy function as shown below.

In [12]:
np.info(np.add)               #  numpy 'info'  function printing the documentation of numpy 'add' function.

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

### 6. Create a null vector of size 10 but the fifth value which is 1

In [14]:
null_vector = np.zeros(10)         # Null vector of size 10.

null_vector[4] = 1                 # Replacing fifth value by value 1.

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7. Create a vector with values ranging from 10 to 49

In [17]:
X = np.arange(10, 49)           # 'arange' is used to create an array with values in a given range.

X

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

### 8. Reverse a vector (first element becomes last)

In [49]:
X[::-1]          # Method 1: Using indexing method to reverse an array

np.flip(X)       # Method 2: Using numpy 'flip' function to reverse an array

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

### 9. Create a 3x3 matrix with values ranging from 0 to 8.

In [80]:
matrix = np.arange(0,9)                         # 
three_matrix = np.resize(matrix, (3,3))

print(three_matrix)
print()
print(three_matrix.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

(3, 3)


### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [5]:
np.nonzero([1,2,0,0,4,0])         # 'nonzero' numpy function returns the indices of elements that are non-zero.

(array([0, 1, 4]),)

### 11. Create a 3x3 identity matrix.

In [4]:
three_identity = np.identity(3)
three_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 12. Create a 3x3x3 array with random values.

In [10]:
random_array = np.random.rand(3,3,3)

print(random_array)
print()
print(random_array.shape)           # Checking the shape of the random_array.

[[[0.2812604  0.28745242 0.08371823]
  [0.9496969  0.30896213 0.09163852]
  [0.87580719 0.17443467 0.43550815]]

 [[0.5909506  0.58092618 0.61842917]
  [0.87741809 0.73763887 0.38678639]
  [0.59411909 0.6974729  0.18930591]]

 [[0.44449727 0.34305043 0.56689231]
  [0.71916837 0.4741575  0.59630422]
  [0.90120362 0.09927224 0.50142571]]]

(3, 3, 3)


### 13. Create a 10x10 array with random values and find the minimum and maximum values.

In [2]:
random_ten_array = np.random.rand(10, 10)
max_value = np.max(random_ten_array)
min_value = np.min(random_ten_array)

print(random_ten_array)
print()
print('Maximum value: ', max_value)
print('Minimum value: ', min_value)

[[0.95430518 0.19344199 0.08312556 0.79353104 0.99242964 0.6538587
  0.13743626 0.44306261 0.52851098 0.35220255]
 [0.64457733 0.09018779 0.60352076 0.44713826 0.8511658  0.95901888
  0.95359339 0.89204496 0.89349501 0.83911331]
 [0.29797021 0.02229476 0.84573804 0.27372797 0.44543301 0.24073298
  0.51770259 0.43128245 0.45373279 0.90444775]
 [0.2603907  0.22311754 0.03028632 0.21069951 0.80962672 0.81037151
  0.61588545 0.4527473  0.49253075 0.00617544]
 [0.4229519  0.54142843 0.65977912 0.85855603 0.81259641 0.59322875
  0.02583466 0.32222042 0.2287542  0.12615421]
 [0.91156619 0.47838905 0.48978484 0.92836022 0.0258248  0.04413118
  0.07305566 0.2752228  0.01140676 0.29892341]
 [0.28383329 0.38017286 0.73912503 0.26994756 0.7825451  0.00295173
  0.53099771 0.37406055 0.13356047 0.73525755]
 [0.58692764 0.69030052 0.13272316 0.76576737 0.53328191 0.9567087
  0.78066841 0.72069189 0.8718469  0.1481126 ]
 [0.61001662 0.94711893 0.37123557 0.73640625 0.98013422 0.1370206
  0.93262008 0.

### 14. Create a random vector of size 30 and find the mean value.

In [3]:
random_vec = np.random.randint(1, 100, (1, 30))
mean_value = np.mean(random_vec)
print(random_vec)
print()
print('Mean value:', mean_value)
print('Size of random_vec is:', random_vec.size)

[[22 93 35 56 63 39 30 33 35 96 10  2 20 39 69 60 26 95 76 22 14 14 81 51
  66 78 55 98 74 70]]

Mean value: 50.733333333333334
Size of random_vec is: 30


### 15. Create a 2d array with 1 on the border and 0 inside

In [30]:
two_dim_array = np.ones((5,5), dtype = 'int')
two_dim_array[1:4,1:4] = 0
two_dim_array

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### 16. How to add a border (filled with 0's) around an existing array?

In [49]:
X = np.random.randint(10, 100, (6,6))
np.pad(X, 1, 'constant', constant_values = 0)   # 'pad' function is used to create a frame/boundary 

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 43, 88, 55, 99, 19, 43,  0],
       [ 0, 24, 45, 97, 27, 71, 10,  0],
       [ 0, 47, 74, 16, 57, 91, 93,  0],
       [ 0, 14, 54, 16, 29, 76, 47,  0],
       [ 0, 39, 80, 22, 48, 19, 13,  0],
       [ 0, 60, 23, 93, 56, 23, 15,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

### 17. What is the result of the following expression? (★☆☆)

<br> 0 * np.nan
<br> np.nan == np.nan
<br> np.inf > np.nan
<br> np.nan - np.nan
<br> np.nan in set([np.nan])
<br> 0.3 == 3 * 0.1

### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal. 

A very simple answer to this question can be achieved by using 'np.diag()' function. 

In [41]:
Z = np.diag(np.arange(1,5),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Another approach but a bit more complicated approach is shown below.

In [34]:
five_matrix = np.arange(10, 35).reshape(5,5)            # Creating a 5 by 5 matrix
print('Example 5*5 matrix is:\n\n', five_matrix)

ex_array = [1,2,3,4]                                    # Elements that we want just below the diagonal



# Using this for loop we will first pick the indices of element in the position just below the diagonal and 
# replace each with 1,2,3 and 4 successively in the original matrix.


for k in range(0,4):                                  
    x, y  = np.where(five_matrix == list(five_matrix.diagonal(-1))[k])  # extracts indices of the elements
    five_matrix[(x,y)] = ex_array[k] 

print('\n\n Changed matrix with 1,2,3,4 just below the diagonal is: \n\n',five_matrix)

Example 5*5 matrix is:

 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]


 Changed matrix with 1,2,3,4 just below the diagonal is: 

 [[10 11 12 13 14]
 [ 1 16 17 18 19]
 [20  2 22 23 24]
 [25 26  3 28 29]
 [30 31 32  4 34]]


### 19. Create a 8x8 matrix and fill it with a checkerboard pattern.

My solution. First create a 2 by 2 identity matrix and expand it to form a 8 by 8 matrix which will resemble a
chckerboard pattern.

In [50]:
two_identity = np.identity(2 , dtype = int)
base_one = np.hstack((two_identity, two_identity, two_identity, two_identity))  # horizontal stacking
checkerboard = np.vstack((base_one, base_one, base_one, base_one))              # vertical stacking
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


This solution is given:

https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md

In [49]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### Easy way is to use "np.unravel_index()" numpy function. Here we specify the position and the shape of an array as an argument. 99 specifies the 100th position as count starts from 0 in python. (6,7,8) is the shape of an array given. 

In [51]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

#### Same result can be acheived by using a logic which uses "np.ravel()" function. This is just like walking the same path above in a different way and arriving at same destination.

In [3]:
# First create an array of unique elements with shape '6,7,8'. Hint: An array of shape '(6,7,8)' will contain 
#  6*7*8 = 336  elements. 

example = np.arange(100, 436).reshape(6,7,8)    

# Identifying the 100th element. Hint: To identify 100th element we first flatten/ravel the array and pick 
# element of index 99 which gives 100th element.

print(np.ravel(example)[99])                    

# Using "np.where" function to get index of the 100th element.

np.where(example == 199)                     

199


(array([1]), array([5]), array([3]))

### 21. Create a checkerboard 8x8 matrix using the tile function.

We have solved similar problem in question number 19 but using a different approach.

In [7]:
sample_array = np.eye(2, dtype = int)   # First creating a 2 by 2 array using "np.eye()" function.
np.tile(sample_array, (4,4))            # Using "np.tile()" function to expand the 2 by 2 array.

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

### 22. Normalize a 5x5 random matrix.

This solution is given in the solution manual. <font color = red> Note: What actually does normalizing a 5 by 5 matrix mean? Am still unclear.

In [16]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.48807629  1.24678856 -0.14569501 -0.93802516  0.64537502]
 [ 0.80177979  0.15346435  1.2251891  -1.15796164 -1.45815559]
 [ 1.00648086 -0.93797865 -0.90919434 -0.45526312 -0.26929948]
 [ 0.33826723  0.436332    0.71132986  1.03609476  1.22695961]
 [ 0.73854178 -1.70296367 -1.26584037  1.09063271 -1.90493491]]


This solution is another solution we find using linear algebra module.

In [17]:
five_matrix = np.random.randint(1, 26, (5, 5))
norm = np.linalg.norm(five_matrix)
normal_matrix = five_matrix/norm

print(normal_matrix)

[[0.11967683 0.15557988 0.22738598 0.11967683 0.26328903]
 [0.21541829 0.20345061 0.05983842 0.01196768 0.21541829]
 [0.11967683 0.1436122  0.08377378 0.21541829 0.10770915]
 [0.21541829 0.23935366 0.25132134 0.28722439 0.16754756]
 [0.10770915 0.28722439 0.22738598 0.28722439 0.28722439]]


### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA).

This exercie aims to introduce us with the concept of data type in numpy. Unlike python, numpy has more number of data types. This question asks us to create a data type to describe a color with four unsigned bytes. Unsigned bytes, denoted by, 'ubyte' tells that the component used to sotre the data in memory is an unsigned number. 

In [11]:
# Creating data type using "np.dtype" numpy function. "np.ubyte" function will indicate that the value used to
# indicate data type is an unsigned byte. 

color_data = np.dtype([('r', np.ubyte),('g', np.ubyte),('b', np.ubyte),('a', np.ubyte)])

# Below is an example of how an array will look like with two different data types: one is int
example1 = np.eye(4, dtype=dg)
example2 = np.eye(4, dtype = int)
print('Array with recently created custom data type\n\n', example1)
print('\n\n Same array created with int64 data type\n\n', example2)


Array with recently created custom data type

 [[(1, 1, 1, 1) (0, 0, 0, 0) (0, 0, 0, 0) (0, 0, 0, 0)]
 [(0, 0, 0, 0) (1, 1, 1, 1) (0, 0, 0, 0) (0, 0, 0, 0)]
 [(0, 0, 0, 0) (0, 0, 0, 0) (1, 1, 1, 1) (0, 0, 0, 0)]
 [(0, 0, 0, 0) (0, 0, 0, 0) (0, 0, 0, 0) (1, 1, 1, 1)]]


 Same array created with int64 data type

 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).

In [36]:
five_three_matrix = np.random.randint(1, 15, (5,3))
print('Five by three matrix:\n\n', five_three_matrix)

three_two_matrix  = np.random.randint(1,6, (3,2))
print('\n\n Three by two matrix:\n\n', three_two_matrix)

product_matrix  = five_three_matrix@three_two_matrix            # @ is used to do matrix multiplication.
print('\n\n Product of two matrices is:\n\n', product_matrix)

Five by three matrix:

 [[14  3 12]
 [ 1  9  9]
 [ 3 14  4]
 [ 8  8 11]
 [12  2  9]]


 Three by two matrix:

 [[1 2]
 [5 2]
 [1 2]]


 Product of two matrices is:

 [[41 58]
 [55 38]
 [77 42]
 [59 54]
 [31 46]]


### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

In [52]:
one_dim_array = np.arange(10, 40)
print('Original one dimensional array \n\n', one_dim_array)
one_dim_array[3:7] = one_dim_array[3:7]*-1
print('\nArray with elements between 3 and 8 being negated. \n\n', one_dim_array)

Original one dimensional array 

 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]

Array with elements between 3 and 8 being negated. 

 [ 10  11  12 -13 -14 -15 -16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39]


### 26. What is the output of the following script? (★☆☆)

<br><br>print(sum(range(5),-1))
<br><br>from numpy import *
<br><br>print(sum(range(5),-1))

In [53]:
print(sum(range(5),-1))

9


In [54]:
from numpy import *
print(sum(range(5),-1))

10


In [58]:
print(range(5), - 1)

range(0, 5) -1


### 27. Consider an integer vector Z, which of these expressions are legal?
<ol>
    <li> Z**Z </li>
    <li> 2 << Z >>2 </li>
    <li> Z < - Z  </li>
    <li> 1j*Z  </li>
    <li> Z/1/1 </li>
    <li> Z < Z > Z </li>
</ol>

In [4]:
Z = np.array([2,3,5,1,11])
Z

array([ 2,  3,  5,  1, 11])

In [3]:
Z**Z

array([           4,           27,         3125,            1,
       285311670611])

In [5]:
2<<Z >>2

array([   2,    4,   16,    1, 1024])

In [6]:
Z<-Z

array([False, False, False, False, False])

In [7]:
1j*Z

array([0. +2.j, 0. +3.j, 0. +5.j, 0. +1.j, 0.+11.j])

In [8]:
Z/1/1

array([ 2.,  3.,  5.,  1., 11.])

In [10]:
Z < Z > Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 28. What are the result of the following expressions? (★☆☆)
<ol>
    <li>np.array(0) / np.array(0)
    <li>np.array(0) // np.array(0)
    <li>np.array([np.nan]).astype(int).astype(float)
</ol>

In [11]:
np.array(0)/np.array(0)

/home/anoj/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [12]:
np.array(0)//np.array(0)

/home/anoj/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [13]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

### 29. How to round away from zero a float array ?

In [9]:
example_array = np.random.uniform(-10,+10,10)    # Create an array picking elements randomly from a uniform 
                                                 # distribution.
    
print('Our example float array is: \n\n', example_array)
print('\n\n Round away aray is \n\n', np.round(example_array))

Our example float array is: 

 [ 2.60722574  2.18052043  2.13422102  0.97643866  4.85161496 -7.96624039
 -4.62594972  5.87137536 -2.38251732  3.42846758]


 Round away aray is 

 [ 3.  2.  2.  1.  5. -8. -5.  6. -2.  3.]


### 30. How to find common values between two arrays? 

This is asking us to find all intersecting elements in any two arrays. Luckily, this job is made easy by the availability of 'np.intersect1d()' numpy function.

In [4]:
array_one = np.random.randint(1,20,(2,3))
array_two = np.random.randint(1, 20,(2,3))
common_values = np.intersect1d(array_one, array_two)
print(array_one)
print('\n\n', array_two)
print('\n\nCommon values between two arrays are: ', common_values)

[[ 6 19 18]
 [ 5  3 13]]


 [[16 14 13]
 [13  3 11]]


Common values between two arrays are:  [ 3 13]


### 31. How to ignore all numpy warnings (not recommended)?

In [2]:
np.ones(10)/0  # This will givewarnings as seen below. 

/home/anoj/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

We can supress warning message in numpy using 'warning' module in numpy using "np.warnings.filterwarnings('ignore')" as shown below.

In [3]:
np.warnings.filterwarnings('ignore')
np.ones(10)/0

array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

<font color = blue>Above method of supressing warning, however, will act everywhere in the code. So, in order to localise the warning supression, we use context manager as shown below. This way, we will keep seeing warning messages outside of this block of code and hence the warning supression won't be universal.

In [2]:
with np.warnings.catch_warnings():
    np.warnings.filterwarnings('ignore')
    np.ones(10)/0

### 32. Is the following expressions true?

In [9]:
np.sqrt(-1) == np.emath.sqrt(-1)

/home/anoj/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

Note: <font color = blue>  "np.emath" is a short form (alias) handling of numpy function "np.lib.scimath". In above particular case, np.sqrt() will not identify the negative square root of any number and give value 'nan'. meaning not a number. However, "np.lib.scimath.sqrt()" understands that square root of negative number is a complex number. So, above statement turns out to be false.

### 33. How to get the dates of yesterday, today and tomorrow?

Numpy has a "datetime64" module for the use of datetime functionality. So using this module we can work on dates and times.

In [13]:
todays_date = np.datetime64('today','D')
print("Today's date is: ", todays_date)
yesterday_date = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("\n\nYeseterday's date is: ", yesterday_date)
tomorrow_date = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("\n\nTomorrow's date is: ", tomorrow_date)


Today's date is:  2021-08-01


Yeseterday's date is:  2021-07-31


Tomorrow's date is:  2021-08-02


### 34. How to get all the dates corresponding to the month of July 2016?

There is a feature in numpy where we can use "arange" function to generate the range of dates. 

https://numpy.org/doc/stable/reference/arrays.datetime.html

In [7]:
july_dates = np.arange('2016-07', '2016-08' , dtype = 'datetime64[D]') # dtype specifies data types. 
print('All dates of the month of July 2016: \n\n',july_dates)

All dates of the month of July 2016: 

 ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In place in numpy means that we don't create a separate memory to store the array. Instead we use the current memory and store the array in it. However, if we create a copy we create a separate memory. 

In [16]:
A = np.ones((3,2))*2             # Creating a 3 by 2 array A of elements 1 and multiplied by 2. 
B = np.ones((3,2))               # Creating a 3 by 2 array B of elements 1

print('Array B\n\n',B)

np.add(A, B, out = B)            # We perform first step of operation of adding two arrays and saving in place.
print('\n\n Array B after being changed to hold the addition of array A and array B\n\n',B)

np.negative(np.divide(A, 2, out = A))   # Second step of operation being performed divide A by 2 and take its
                                        # negative.
np.multiply(B, A, out = B)              # Third step of operation being performed. Multiply (A+B) and (-A/2)       
print('\n\n Array B after being changed to contain the product of B and A\n\n',B)

Array B

 [[1. 1.]
 [1. 1.]
 [1. 1.]]


 Array B after being changed to hold the addition of array A and array B

 [[3. 3.]
 [3. 3.]
 [3. 3.]]


 Array B after being changed to contain the product of B and A

 [[3. 3.]
 [3. 3.]
 [3. 3.]]


### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

What the question means is that suppose we have an array of random float numbers. Our job is to extract only the integer part of those floating numbers in the array. There are several ways we can do this in numpy. We can either be tricky and use arithmetic technique or use already available numpy functions to extract only the integer part. 

In [3]:
A = np.random.uniform(20,300, (2,3))   # Lets us create any array with floating point positive integers.
print(A)

[[ 37.86627374 200.97890298 134.1452914 ]
 [ 85.45272555 270.98297507 126.20528597]]


In [4]:
method_one = np.floor(A).astype('int32')   # First method makes use of "floor" function in numpy
print(method_one)

[[ 37 200 134]
 [ 85 270 126]]


In [5]:
method_two = np.ceil(A).astype('int32') - 1   # Second method is bit tricky and makes use of "ceil" function
print(method_two)

[[ 37 200 134]
 [ 85 270 126]]


In [6]:
method_three = np.floor(A//1).astype('int32') # Third method makes use of floor division.
print(method_three)

[[ 37 200 134]
 [ 85 270 126]]


In [7]:
method_four = (A - A%1).astype('int32')       # Fourth method makes use of percentage divison.
print(method_four)

[[ 37 200 134]
 [ 85 270 126]]


### 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [3]:
A = np.arange(0, 5)      # Creating a row elements ranging from 0 to 4
B = (np.ones((5,5))*A)   # Creating an array of elements ones and multiply by row created above.
                                       
print(B)

C = B.astype('int32')    # We then convert the array to 'int32' data type.
print('\n\n Integer form of the array above.\n\n', C)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


 Integer form of the array above.

 [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 38. Consider a generator function that generates 10 integers and use it to build an array.

<font color = red> This question wants to introduce us to generator function in python and use it to create an array. Below I have written two examples of generator function. 

In [34]:
def first_generator_function():        # First generator function
    for k in range(4,10):
        yield k

In [35]:
for val in first_generator_function():
    print(val, end = ' ')

4 5 6 7 8 9 

In [32]:
def second_generator_function():              # Second generator function
    n = 1
    print('The first value of n is', n)       # prints value 1
    
    yield n
    
    n +=1
    
    print('The second value of n is:', n)     # prints value 2
    
    yield n
    
    n +=1
    print('The second value of n is:', n)      # prints value 3
    
#     yield n

In [36]:
xyz = second_generator_function()     # I have shown StopIteration error below intentionally to exhibit that 
next(xyz)                             # generator function will stop iterating once no yield statement is 
next(xyz)                             # encountered. 
next(xyz)

The first value of n is 1
The second value of n is: 2
The second value of n is: 3


StopIteration: 

<font color = #7f1020> BELOW IS THE ACTUAL ANSWER OF THE QUESTION

In [2]:
def generator_function():                               # Generator function
    for num in range(1, 11):
        yield num
    

number_list = [val for val in generator_function()]     # creating list from use of generator function above
print('A list of number from 1 to 10:', number_list)

number_array = np.array(number_list, dtype = 'int32')   # creating a numpy array using the list above.
print('\n An array is created')
number_array

A list of number from 1 to 10: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

 An array is created


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [6]:
vector = np.random.rand(10)
print(vector)

[0.28352222 0.86501053 0.66782166 0.20348107 0.05465955 0.32172766
 0.37279788 0.58267781 0.13776992 0.31672379]


### 40. Create a random vector of size 10 and sort it

In [19]:
vector = np.random.randint(1, 100, 10)
print('Random vector of size 10', vector)
sorted_vector = np.sort(vector)
print('\n\n Above vector after being sorted out ', sorted_vector)

Random vector of size 10 [56 55 79 33 66 68 11  1 73 47]


 Above vector after being sorted out  [ 1 11 33 47 55 56 66 68 73 79]


### 41. How to sum a small array faster than np.sum?

The answer is given in the link below. Since 'np.sum' ultimately goes through 'np.add.reduce',for smaller arrays it is faster to use 'np.add.reduce'.

https://stackoverflow.com/questions/16420097/what-is-the-difference-between-np-sum-and-np-add-reduce

In [25]:
example_array = np.arange(1, 20)
np.add.reduce(example_array)

190

### 42. Consider two random array A and B, check if they are equal

In [35]:
array_A = np.random.randint(10, 50, 10)
array_B = np.random.randint(10,50, 10)

np.equal(array_A, array_B)    # Checks if each element of two array are equal

array([False, False, False, False, False, False, False, False, False,
       False])

### 43. Make an array immutable (read-only)

Check this link below for detailed discussion. The basic idea is that numpy arrays are inherently mutalbe. We can make use of 'flags' function to make it immutable. 

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flags.html

In [7]:
example_array = np.arange(1, 10)
print('This is our example array', example_array)
example_array.flags.writeable = False               # This tells that array is now no longer writeable. 
example_array[3] = 12               # Trying to assign new value at any positioin of array will return error.

This is our example array [1 2 3 4 5 6 7 8 9]


ValueError: assignment destination is read-only

### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [98]:
random_matrix = np.random.randint(1, 10, (10,2))
print('Cartesian coordinates: \n\n',random_matrix)

# Separating X and Y co-ordinates

x_coordinates = random_matrix[:, 0]
y_coordinates = random_matrix[:, 1]

# Finding polar radius according to the formula stated above

polar_radius = np.round(np.sqrt(x_coordinates**2 + y_coordinates**2),2)

# Finding polar angle according to the formula stated above

polar_angle = np.round(np.arctan(y_coordinates/x_coordinates)*(180/np.pi), 2)


polar_coordinates = np.array([[polar_radius],[polar_angle]], ndmin=2).reshape(2,10)
print('\n\nCorresponding polar Cordinates are:\n\n', polar_coordinates)

Cartesian coordinates: 

 [[9 5]
 [4 5]
 [5 9]
 [7 3]
 [8 1]
 [3 5]
 [5 5]
 [2 3]
 [9 7]
 [8 2]]


Corresponding polar Cordinates are:

 [[10.3   6.4  10.3   7.62  8.06  5.83  7.07  3.61 11.4   8.25]
 [29.05 51.34 60.95 23.2   7.13 59.04 45.   56.31 37.87 14.04]]


### 45. Create random vector of size 10 and replace the maximum value by 0

Here I will make use of 'np.where' function to get the index of maximum value of array and replace it by 0.

In [27]:
random_vector = np.random.randint(10, 50, 10)                   # Creating a random array of size 10.
print(random_vector)
max_value = np.max(random_vector)                               # Identifying maximum value
print(f'\n\n Maximum value {max_value}')         
index_value = np.where(random_vector == max_value)              # Using np.where to get an index of max value
random_vector[index_value] = 0                                  # Max value being replaced with 0
print('\n\nRandom array with maximum value replaced\n\n', random_vector)

[37 45 17 18 31 23 17 19 43 38]


 Maximum value 45


Random array with maximum value replaced

 [37  0 17 18 31 23 17 19 43 38]


### 46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.

<font color = 'red'>About Structured Array</font>

Structured Array: In general we define array using standard numpy function. Arrays defined that way will have a predefined structure and generally contains elements as single identity. For example:

Example Numpy Array

[[1 , 2, 3]
[4, 11, 5]]

Suppose we want an array where each unit contains different types of data in an ordered pair. For instance we want to deinfe array as below.

Example Structured Array

[[ ('Jason', 11, 150), ('Anoj', 25, 165)]
[('Anisha', 20, 163), ('Jenisha', 15, 168)]
[('Nabin', 10, 159), ('Anita', 16, 165)]]

This array we just defined is called a structured array. Numpy allows us to define an array in our own way when We  have to insert several data types in each unit of the array. In structured array above,each unit of the array contains 'name', 'grade' and 'height' of students in a ordered pair ('name', 'garde', 'height'). So, basically, structured array is customized array that we can define in numpy when we need to create an array to hold data types the way we want. For more see:  https://numpy.org/doc/stable/user/basics.rec.html


<font color = 'orange'> What is question asking us? </font>

This question asks us to create a structured array that will have data type (x,y) in each unit. And, each data should lie in between 0 to 1. [0,1]x[0,1] means (x,y) x value should lie between o to 1 and y value should lie between 0 to 1 as well. There is no restriction of the shape of array so we can create array of any shape we please.

In [42]:
Z = np.zeros((6,6), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,6), np.linspace(0,1,6))
print(Z)

[[(0. , 0. ) (0.2, 0. ) (0.4, 0. ) (0.6, 0. ) (0.8, 0. ) (1. , 0. )]
 [(0. , 0.2) (0.2, 0.2) (0.4, 0.2) (0.6, 0.2) (0.8, 0.2) (1. , 0.2)]
 [(0. , 0.4) (0.2, 0.4) (0.4, 0.4) (0.6, 0.4) (0.8, 0.4) (1. , 0.4)]
 [(0. , 0.6) (0.2, 0.6) (0.4, 0.6) (0.6, 0.6) (0.8, 0.6) (1. , 0.6)]
 [(0. , 0.8) (0.2, 0.8) (0.4, 0.8) (0.6, 0.8) (0.8, 0.8) (1. , 0.8)]
 [(0. , 1. ) (0.2, 1. ) (0.4, 1. ) (0.6, 1. ) (0.8, 1. ) (1. , 1. )]]


In [39]:
structured_array = np.zeros((3,3), dtype = [('x_coordinate', float), ('y_coordinate', float)])
structured_array['x_coordinate'], structured_array['y_coordinate'] = np.meshgrid(np.linspace(0, 1, 3), np.linspace(0,1,3))

In [41]:
print(structured_array)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


In [3]:
structured_array = np.array([[(3 ,3), (3,3), (3,3)], [(3 ,3), (3,3), (3,3)], [(3 ,3), (3,3), (3,3)]], dtype = [('x_coordinate', float), ('y_coordinate', float)])
structured_array['x_coordinate'], structured_array['y_coordinate'] = np.meshgrid(np.linspace(0, 1, 3), np.linspace(0,1,3))

In [4]:
structured_array

array([[(0. , 0. ), (0.5, 0. ), (1. , 0. )],
       [(0. , 0.5), (0.5, 0.5), (1. , 0.5)],
       [(0. , 1. ), (0.5, 1. ), (1. , 1. )]],
      dtype=[('x_coordinate', '<f8'), ('y_coordinate', '<f8')])

### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [15]:
X = np.random.randint(5, 20, (2,3))                 # Any matrix X
Y = np.ones((2,3), dtype= 'int')                    # Any matrix Y
C = 1/(X-Y)                                         # Cauchy Matrix formed out of X and Y.

In [21]:
print('Matrix X: \n\n',X)
print('\n\nMatrix Y: \n\n',Y)
print('\n\nCauchy Matrix: \n\n',C)

Matrix X: 

 [[16 14  9]
 [ 9 10 12]]


Matrix Y: 

 [[1 1 1]
 [1 1 1]]


Cauchy Matrix: 

 [[0.06666667 0.07692308 0.125     ]
 [0.125      0.11111111 0.09090909]]


### 48. Print the minimum and maximum representable value for each numpy scalar type.

What this question is asking us is to find the maximum and minimum value that is supported by each numpy calar. While creating an array each element of a given array should be uniform. For example it could by integer type, float types, etc. In case of integer types there are 'int8', 'int16', 'int32', etc. This tells us that it contains 8 bits, 16 bits etc. This is not important for this question. We only want to know what is the range of values supported by these data types. Similarly we could also find for float types as 'float32', 'float64', etc.

There is a numpy function which helps us to gather inforamtion about it. For integer data types we use 'iinfo' and for float data types we use 'finfo'. For instance, if we want to know the maximum representable supported by 'int32' data types we can get it by using 'np.iinfo('int32').max'. Here, in this code I have used for loop to make it easier to gather values of integer and float data types.

In [3]:
from colorama import Back, Style, Fore

print(Back.CYAN,'Below are the maximum and minimum representable value for integer types.')
print(Style.RESET_ALL)
for val in ('int8', 'int16', 'int32', 'int64'):
    print(f'SCALAR TYPE: {val}')
    print(f'Maximum representable value for {val} scalar type is {np.iinfo(val).max}\n')
    print(f'Minimum representable value for {val} scalar type is {np.iinfo(val).min}\n\n')

print(Back.GREEN, 'Below are the maximum and minimum representable value for float types.')
print(Style.RESET_ALL)

for val in ('float32', 'float64'):
    print(f'SCALAR TYPE: {val}')
    print(f'Maximum representable value for {val} scalar type is {np.finfo(val).max}\n')
    print(f'Minimum representable value for {val} scalar type is {np.finfo(val).min}\n\n')

    

 Below are the maximum and minimum representable value for integer types.

SCALAR TYPE: int8
Maximum representable value for int8 scalar type is 127

Minimum representable value for int8 scalar type is -128


SCALAR TYPE: int16
Maximum representable value for int16 scalar type is 32767

Minimum representable value for int16 scalar type is -32768


SCALAR TYPE: int32
Maximum representable value for int32 scalar type is 2147483647

Minimum representable value for int32 scalar type is -2147483648


SCALAR TYPE: int64
Maximum representable value for int64 scalar type is 9223372036854775807

Minimum representable value for int64 scalar type is -9223372036854775808


 Below are the maximum and minimum representable value for float types.

SCALAR TYPE: float32
Maximum representable value for float32 scalar type is 3.4028234663852886e+38

Minimum representable value for float32 scalar type is -3.4028234663852886e+38


SCALAR TYPE: float64
Maximum representable value for float64 scalar type is 

### 49. How to print all the values of an array?


Generally, when we have an array of large size, numpy condenses the array and only shows few values. But if we want to see all the values in an array we use 'set_printoptions()' numpy function and set threshold in it to see the range of values we want to see. If we want to see all the values in an array we set 'threshold' value to be 'np.inf'  

In [6]:
X = np.random.randint(10, 50, (50,30))
print(X)

[[40 28 14 ... 33 39 48]
 [19 46 37 ... 38 32 33]
 [28 25 49 ... 23 16 46]
 ...
 [27 44 24 ... 13 11 41]
 [28 23 12 ... 44 26 32]
 [39 27 49 ... 11 42 16]]


In [7]:
np.set_printoptions(threshold=np.inf)
print(X)

[[40 28 14 38 44 13 11 24 30 44 27 43 32 21 32 33 46 22 39 37 30 22 14 33
  18 49 28 33 39 48]
 [19 46 37 32 10 13 10 23 42 37 26 17 47 41 41 25 33 39 24 49 25 17 42 40
  38 18 17 38 32 33]
 [28 25 49 34 21 46 17 12 10 37 36 43 44 34 30 28 22 38 29 31 47 49 35 19
  40 43 43 23 16 46]
 [32 44 49 17 28 15 42 28 13 49 14 10 27 39 46 23 33 21 49 43 18 34 14 33
  16 27 16 32 42 31]
 [18 15 40 49 27 12 47 37 33 23 19 42 14 10 17 34 17 24 47 15 26 40 20 40
  42 48 39 33 29 20]
 [11 33 37 25 25 45 21 30 36 29 43 14 36 28 11 22 38 41 27 35 41 25 47 21
  28 34 29 31 46 24]
 [33 18 39 44 28 49 45 21 14 46 37 46 24 15 16 25 42 38 18 28 17 32 39 43
  16 25 39 43 22 19]
 [43 12 11 19 42 28 35 25 33 21 49 19 11 41 19 46 32 18 19 26 44 12 41 29
  22 23 13 28 46 20]
 [11 27 46 27 39 44 16 24 40 31 29 47 39 29 49 18 40 34 28 32 31 31 39 12
  35 36 46 37 30 40]
 [17 26 32 12 19 39 16 41 21 47 21 44 17 15 44 44 28 37 24 47 37 27 35 34
  12 20 42 24 30 25]
 [24 14 39 23 49 28 10 16 28 26 18 25 38 18 17 47 

### 50. How to find the closest value (to a given scalar) in a vector?

In [38]:
example_array = np.random.randint(10, 1000, (18,18))
print(example_array)

[[982 305 588 924 890 589  81 941 436 993  86 623  54  12  64 861 158 867]
 [544 108 937 336 222 143 602 735 209 193 556 763 882 806 620 898  42 342]
 [128 765 550 567  88 481 420 839 225  42 267 687 434 142 237 681 308 304]
 [420 244 852 898 831 929  10 411 211 234 479  46 787  24 686 620 730 581]
 [853 325 899 868 947 404 816 490 602 135 150 700  45 475 486 898 997 191]
 [436 402 647 711 299 971 378 768  35 156 421 986 905 918 660  69 256 739]
 [844  33 501 711 825 933 530 809 541 368 668 908  96 574 197 369 814  75]
 [644 842 195 538 387  31 616 707 237 242 220 394 206 236 616 757 496 439]
 [847 243 577 871 527 815 396 676 698 507 770 483 591 923 757 389 831 308]
 [570 584 333  33 412 784 593 233 165 127 141  89 334 383 461 528 937 848]
 [702 380 520 514 402  94 272 762 986 467 257 164 312 757 585 381 451 271]
 [678 811 147 496 798 815  80 268  88 584  43 587 775 539 552 371 993 785]
 [170 437  27  61 805 521 534 819 654 841 484 820 281 180 108 712 874 192]
 [180 333 568 939 268 152

<font color = red>Let me elaborate what question is asking us:</font>

Suppose we have any given value 121. We also have an array as shown above and we want to find a value in the array which is nearest(or closest) to 121. How do we do it? When the size of array is small we can simply look manually and identify the nearest value in an array to a given value. But when we have an array that is pretty large it becomes tedious and it almost impossible to find the required value. 

<font color = green> The magic for this problem is mainly done by "np.argmin()" function which pulls out the index for a minimum value</font>

In [40]:
example_array = np.random.random_integers(10, 1000, (18 ,18))     # Creating an array
print(example_array)
test_value = 121                                                  # Sample test value



'''In order to identify the nearest value we take the differenece of given value with each value and find 
absolute values of each of them. While doing so, the nearest value will be the one that will have the least 
value of difference.
'''

difference = example_array - test_value
array_of_abs_values = np.abs(difference)  

# 'argmin()'  function is in-built numpy function that will pick the index of the minimum value from given array
index_of_closest_value = array_of_abs_values.argmin()

print('\n\n Index of closest value:', index_of_closest_value)

closest_val = np.ravel(example_array)[index_of_closest_value]

print('\n\n Closest Value to 121 in a given array is: ', closest_val)

[[790 939 179 723 858  40 518 604 602 261 593 523 663  60 658 835 394 169]
 [307  53 865 203 820 499 519 906 891 225 639 568 155 352 625 130 480 859]
 [354 796 100 787  88 503 144 633 532 682 408 286 583  65 614 555 776 947]
 [147  63 221 518 448 326 476 657 744 126 824 324 382 903 682 938 939  18]
 [111 224 349 699 669 453 337 595 600 980 205 760 896 224  33 698 106 106]
 [513 309 988 682 345 326  60 416 736 488 514 292 321 131 616 156 472 534]
 [767 703 639 536 241 972 615 751 958 914 318 566 871 118 180 319 305  67]
 [231 386 184 403 440 273 585 961 424 627 335 137 285 280 606 360 447 931]
 [ 85 259 726 461 732 147 148  51 835 516 924 556 664  79 327 629 241 359]
 [554 412  97 890 855 961 835 823 727 842 551 118 186 534 912 604 545 715]
 [339 975 970 966 881 654  36 889 698 959 316 671 736 445  37 787 666 572]
 [ 87 243 983 717 136 358 277 545 361 903 205 774  57  38 224 370 862 567]
 [758 627 993 429 420 751 122  92 348 462 331 957 237 786 451 888 476 127]
 [ 61 292 392 456 518 646

/home/anoj/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(10, 1000 + 1) instead
  """Entry point for launching an IPython kernel.


### 51. Create a structured array representing a position (x,y) and a color (r,g,b).

This is related to question number 48 where we learnt how to create a structured array.

In [26]:
pos_color_structured_array = np.zeros((3,3), [('x', float),('y', float),
                                              ('r', float),('g', float), ('b', float)])

print('\nFirst two component represent position and last three componnent will represent color.\n\n')
print(pos_color_structured_array)


First two component represent position and last three componnent will represent color.


[[(0., 0., 0., 0., 0.) (0., 0., 0., 0., 0.) (0., 0., 0., 0., 0.)]
 [(0., 0., 0., 0., 0.) (0., 0., 0., 0., 0.) (0., 0., 0., 0., 0.)]
 [(0., 0., 0., 0., 0.) (0., 0., 0., 0., 0.) (0., 0., 0., 0., 0.)]]


#### Or we could also create this array as below.


In [27]:
pos_color_array = np.zeros(4, [('position', [('x', float), ('y', float)]), 
                          ('color', [('r', float),('g', float),('b', float)])])
print(pos_color_array)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


### 52. Consider a random vector with shape (10,2) representing coordinates, find point by point distances.

Below is a set of co-ordinate points. We are being asked to find distances of each point with all other points and the point itself.

In [47]:
rand_vect = np.random.rand(10, 2)
print(rand_vect)

[[0.05623544 0.70133831]
 [0.80813772 0.63376013]
 [0.50382821 0.10451781]
 [0.10736379 0.57053532]
 [0.30180844 0.02247691]
 [0.35847852 0.28898181]
 [0.22440725 0.41994377]
 [0.36930548 0.18176316]
 [0.70198891 0.17455165]
 [0.94312147 0.97986714]]


This is more numpyish way of doing the same thing.

In [46]:
X,Y = np.atleast_2d(rand_vect[:,0], rand_vect[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.77588809 0.66989329 0.18556135 0.78395137 0.68754368
  0.30972598 0.32119041 0.55838693 0.93739363]
 [0.77588809 0.         0.42562356 0.79320829 0.37391744 0.59557259
  0.48375564 0.49101081 0.38333591 0.5318521 ]
 [0.66989329 0.42562356 0.         0.58461641 0.74393161 0.17025554
  0.38753927 0.36157152 0.12588814 0.26814414]
 [0.18556135 0.79320829 0.58461641 0.         0.88197072 0.56086738
  0.31229603 0.30221285 0.49513314 0.84178785]
 [0.78395137 0.37391744 0.74393161 0.88197072 0.         0.90198114
  0.59556484 0.62305322 0.65593225 0.90004216]
 [0.68754368 0.59557259 0.17025554 0.56086738 0.90198114 0.
  0.45723127 0.42363783 0.24923629 0.3088952 ]
 [0.30972598 0.48375564 0.38753927 0.31229603 0.59556484 0.45723127
  0.         0.03619465 0.26486654 0.65343505]
 [0.32119041 0.49101081 0.36157152 0.30221285 0.62305322 0.42363783
  0.03619465 0.         0.24179695 0.62892855]
 [0.55838693 0.38333591 0.12588814 0.49513314 0.65593225 0.24923629
  0.26486654 0.24179

This is not very numpyish way but more pythonic way and is not recommended when we have huge data set. Remember, numpy is always faster and more efficient when we have to deal with large data set.

In [43]:
for m in range(0, rand_vect.shape[0]):
    point = rand_vect[m]
    print('\n\n Point Distances for the Reference Point', (point[0],point[1]))
    print('\n')
    for n in range(0, rand_vect.shape[0]):
        dist = np.sqrt((point[0] - rand_vect[n][0])**2 + (point[1] - rand_vect[n][1])**2)
        print('Distance between reference point and',(rand_vect[n][0], rand_vect[n][1]), '\t', dist)



 Point Distances for the Reference Point (0.8290475126214805, 0.08550183860146399)


Distance between reference point and (0.8290475126214805, 0.08550183860146399) 	 0.0
Distance between reference point and (0.14199294342900826, 0.4459992059612594) 	 0.775888093040225
Distance between reference point and (0.5033510980384046, 0.6708896290191653) 	 0.669893289742769
Distance between reference point and (0.9110961127050806, 0.25193813696345946) 	 0.18556134885293793
Distance between reference point and (0.045096407579718556, 0.08485475598689285) 	 0.7839513720965795
Distance between reference point and (0.6539176265448949, 0.7503671142975903) 	 0.6875436799387249
Distance between reference point and (0.6019383218641843, 0.2961000286421479) 	 0.3097259791732782
Distance between reference point and (0.6186633368847236, 0.32819872925162674) 	 0.3211904141341887
Distance between reference point and (0.512239691829023, 0.5453156820577489) 	 0.5583869321082888
Distance between reference point

### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?


In [6]:
float_array = (np.random.rand(10)*55).astype('float32')            # Creating any float data type array.

# Naturally array created will be of 'float64' datatype. So we change it to 'float32' data type using 'astype()'
# method

print(float_array)
float_array.dtype     # Checking if array is in 'float32' data type.

[29.267424 19.620466 30.66615  26.526766 50.405693  6.819016  7.176138
 53.1212    4.198858 17.034689]


dtype('float32')

In [10]:
modified_array = float_array.astype('int32') # Converting to 'int32' data type.
print(modified_array)
modified_array.dtype

[29 19 30 26 50  6  7 53  4 17]


dtype('int32')

### 54. How to read the following file?

1, 2, 3, 4, 5 <br>
6, <t> , <t> , 7, 8 <br>
, <t> , 9, 10, 11

In this exercise we are asked how we can read file of a given type to a numpy array. It is not in a numpy array format and we need to conver it to a numpy array data type. So, how do we do this? We make use of two functionalities. One is 'StringIO' method from 'io' python module.  This will help us to read string. We then generate numpy array from the text thus created using 'io' module. For this purpose we use 'np.genfromtxt()' method of numpy. This method helps us to create an array from a text. 

In [17]:
from io import StringIO

# Convert given file to a string using 'StringIO' method in 'io' module

sample_string = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11''')
        

txt_array = np.genfromtxt(sample_string, delimiter=',', dtype = 'int32', filling_values=0) 

# Empty positions are filled with value 0.

print(txt_array)
type(txt_array)

[[ 1  2  3  4  5]
 [ 6  0  0  7  8]
 [ 0  0  9 10 11]]


numpy.ndarray

### 55. What is the equivalent of enumerate for numpy arrays?

In python we have an 'enumerate()' function that iterates over a iterable by giving its value and serial count. In numpy we have 'ndenumerate()' function that will specify the positional location of an element in array in an iterative way as shown in the example below. 

In [11]:
z = np.random.randint(3, 20,(3,4))      # Creating any array
print(z)

[[ 3 17 18 18]
 [10  5 14  9]
 [18  3 13 12]]


In [13]:
'''  Using 'np.ndenumerate()' numpy function to create an iterable. We can see in the example below every element 
 is being specified with its location with (x,y) ordered pair where 'x' is its index along x-axis and 'y' is
 its index along y-axis'''

for k in np.ndenumerate(z):
    print(k)

((0, 0), 3)
((0, 1), 17)
((0, 2), 18)
((0, 3), 18)
((1, 0), 10)
((1, 1), 5)
((1, 2), 14)
((1, 3), 9)
((2, 0), 18)
((2, 1), 3)
((2, 2), 13)
((2, 3), 12)


### 56. Generate a generic 2D Gaussian-like array

In this example I will create a 5 by 5 Gaussian array generated manually. The main ideas behind the creation of 
generic Gaussian array is that we make use of the Gaussian function below to do this. 

$$  f(x) = \exp{\Big[-\frac{(x - \mu)^2}{2\sigma^2}\Big]}   $$

This gives us a bell shaped curve. Our aim here is to generate array that contains elements which will represent those Gaussian points. 

<font color = red> Need more elaborate explaination with plotting of generic Gaussian points generated below.<\font>

In [36]:
x, y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))
distance = np.sqrt(x**2 + y**2)
sigma, mu = 1, 0

generic_gaussian = np.exp(-(distance - mu)**2/2*sigma**2)
print(generic_gaussian)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


### 57. How to randomly place p elements in a 2D array?

Here we make use of two numpy functions. One is <font color = blue> 'np.random.choice()' </font> function will give us list of integers which we will use to indicate the position where we want to place our p number of elements in any array. 
    
Another function we use is <font color = blue> np.put() </font>. This function will let us PUT any element 'x'(integer) in specified positions. 

In [2]:
import numpy as np
y1 = np.random.randint(20, 30, (4,5))
print('Array y1 before being randomly placed with p elements \n\n', y1)
x1 = np.random.choice(10, 5, replace = False)
print('\n\n Elements will be placed at these locations of array y1 \n\n', x1)
np.put(y1, x1, 555 )
print('\n Array y1 after being randomly placed with p elements. Here the element being placed is 555 \n\n', y1)

Array y1 before being randomly placed with p elements 

 [[22 26 28 25 26]
 [21 23 29 20 23]
 [23 26 27 20 22]
 [28 20 20 21 20]]


 Elements will be placed at these locations of array y1 

 [8 3 7 4 1]

 Array y1 after being randomly placed with p elements. Here the element being placed is 555 

 [[ 22 555  28 555 555]
 [ 21  23 555 555  23]
 [ 23  26  27  20  22]
 [ 28  20  20  21  20]]


### 58. Subtract the mean of each row of a matrix.

In [11]:
sample_matrix = np.random.randint(10, 50, (3,4))
print('Any sample matrix chosen\n\n',sample_matrix)
mean_values = np.mean(sample_matrix, axis = 0)
print('\n\n Mean values taken along the vertical axis', mean_values)
new_matrix = sample_matrix - mean_values
print('\n\n Matrix after the mean values are subtracted \n\n', new_matrix)

Any sample matrix chosen

 [[12 14 25 31]
 [29 18 10 31]
 [45 40 28 49]]


 Mean values taken along the vertical axis [28.66666667 24.         21.         37.        ]


 Matrix after the mean values are subtracted 

 [[-16.66666667 -10.           4.          -6.        ]
 [  0.33333333  -6.         -11.          -6.        ]
 [ 16.33333333  16.           7.          12.        ]]


### 59. How to sort an array by the nth column?

In this question we are asked to sort whole array based on the sorting index of any particular column. So, what we do is first find the sorting index of nth column. For this we use <font color = blue>'np.argsort()'</font> method in numpy which returns indices of given column. We then use this as our reference index to sort the whole array. 

In [44]:
example_array = np.random.randint(1, 20, (6,6))   # Creating any 6 by 6 array.
print('Our sample array \n\n', example_array)

Our sample array 

 [[18 11 16  1  8  9]
 [ 1  7 19 17 13 10]
 [16 13  2 18  1 10]
 [ 2 12  4 18  6  7]
 [16 12  7  9 14  5]
 [ 8  4 14  6 13 12]]


In [45]:
# Finding sorting indices of fifth column. We will use this as a reference to sort all other columns of our 
# sample array. 

sorting_index_fourth_column = np.argsort(example_array)[:,4]  
print('Our sorting indices of fifth column is: \n\n',sorting_index_fourth_column)
print('\n\n Below is a sorted array based on the above sorting indices')
example_array[sorting_index_fourth_column]

Our sorting indices of fifth column is: 

 [2 3 0 1 4 4]


 Below is a sorted array based on the above sorting indices


array([[16, 13,  2, 18,  1, 10],
       [ 2, 12,  4, 18,  6,  7],
       [18, 11, 16,  1,  8,  9],
       [ 1,  7, 19, 17, 13, 10],
       [16, 12,  7,  9, 14,  5],
       [16, 12,  7,  9, 14,  5]])

### 60. How to tell if a given 2D array has null columns?

In [20]:
sample_array = np.random.randint(0, 5, (4,5))
print('Some random array is created for testing \n\n',sample_array)
column_axis = sample_array.any(axis = 0)

# 'array.any()' function will check for null values along the axis specified and returns 'True' or 'False'
# result accordingly. Setting axis = 0 will check along the columns of an array.If any of the column will have
# null values it will return 'False' for that column.

print('\n\nTesting if any of the column has null axis\n\n', column_axis)

Some random array is created for testing 

 [[4 4 2 4 4]
 [1 2 3 4 4]
 [1 4 0 2 4]
 [2 0 3 3 3]]


Testing if any of the column has null axis

 [ True  True  True  True  True]


### 61. Find the nearest value from a given value in an array.

<font color = 'purple'>This question has already been done in question number 50.</font>

### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In this question we make use of  <font color = blue>'np.nditer()'</font>  function to iterate over the elements of an array and find their sum. <font color = blue>'np.nditer()'</font>  function is used to iterate over all the elements of an array. 

In [52]:
one_by_three_array = np.random.randint(10, 50, (1,3))
print('Below is a sample one by three array \n\n',one_by_three_array)
three_by_one_array = np.random.randint(1, 10, (3,1))
print('\n\n Below is a sample three by one array \n\n', three_by_one_array)

# Finding sum of elements of  one by three array.

k1 = 0
for m in np.nditer(one_by_three_array):
    k1 = k1 + m
print('\n\nSum of all the elements in one by three array is: \t', k1)

# Finding sum of elements of  three by one array.

k2 = 0
for n in np.nditer(three_by_one_array):
    k2 = k2 + n
print('\n\nSum of all the elements in three  by one array is: \t', k2 )

Below is a sample one by three array 

 [[21 30 46]]


 Below is a sample three by one array 

 [[4]
 [9]
 [9]]


Sum of all the elements in one by three array is: 	 97


Sum of all the elements in three  by one array is: 	 22


### 63. Create an array class that has a name attribute.

This question requires some knowledge of object oriented programming and sbuclassing. Below is the link to numpy tutorial which details on how we can subclass ndarray. You can especially see subsection titled "Slightly more realistic example - attribute added to existing array"  to get a precise code. 

https://numpy.org/doc/stable/user/basics.subclassing.html#slightly-more-realistic-example-attribute-added-to-existing-array



<font color = blue>Our main goal for this question is we want to create an array class that has name attribute. So, when we call a particular method of this class it will give name of that array. In the example shown below my array class is named - 'ArrayClass_with_NameAttribute' and the attribute to get the name of the arary can be done by calling  'array_name' method. If no name is give array will have name 'Example_Array'</font>

In [40]:
import numpy as np

class ArrayClass_with_NameAttribute(np.ndarray):

    def __new__(cls, input_array, array_name = 'Example_Array'):
        obj = np.asarray(input_array).view(cls)
        obj.array_name = array_name                             # array_name instance is added
        return obj                                              # returning newly created instance: array_name

    def __array_finalize__(self, obj):
        if obj is None: return
        self.array_name = getattr(obj, 'array_name', 'Example_Array')

In [41]:
random_array = np.random.randint(1, 10, (2,3))   # Creating any random array.

''' We are creating any class object named - 'named_array'. In this example name of the array is 'NumpyRocks'.

'''

named_array = ArrayClass_with_NameAttribute(random_array, 'NumpyRocks')

In [42]:
named_array.array_name     # This should give the name of object - named_array

'NumpyRocks'

In [43]:
unnamed_array = ArrayClass_with_NameAttribute(np.arange(10))  # No name is given for this object.
print(unnamed_array)                                 
unnamed_array.array_name    # Since no name was given for the 'array_name' attribute it returns predefined name.

[0 1 2 3 4 5 6 7 8 9]


'Example_Array'

### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with                    repeated indices)?

Elaborating Question:

Suppose there is a vector A. We have another vector B and we have to assume that elements of these vectors indicate the index position in vector A. For each index position specified by element in B, we add 1 to that element in A with that index position. If any index position is repeated we add 1 repeatedly to corresponding element in A.   

In [4]:
import numpy as np
value_one_array = np.ones(5)             # Creating a simple 5 by 1 array with 1 as its elements
print('Our first vector A is: \n\n',value_one_array)
random_array = np.random.randint(0, 5, 15)
print('\n\nOur reference vector B which specifies the index positions is: \n\n',random_array)

Our first vector A is: 

 [1. 1. 1. 1. 1.]


Our reference vector B which specifies the index positions is: 

 [2 4 4 3 4 1 3 1 1 3 1 4 1 3 4]


Here second vector B gives the index positions. For instance, index position 3 appears 4 times. Different index positions randomly repeats different number of times. Our job here is to find how many number of times each index position repeat and add that many 1 to corresponding index position element in vector A. To find out how many times each index position repeats we make use of <font color = blue>'np.bincount()'</font> function. Go to this link for more details on this function. 

https://numpy.org/doc/stable/reference/generated/numpy.bincount.html

In [10]:
# Using 'np.bincount()' function to find out the number of times each index position repeats.

index_count = np.bincount(random_array, minlength = 5)

print('Below we get the number of times each index position repeats\n\n', index_count)

Below we get the number of times each index position repeats

 [0 5 1 4 5]


In reference vector B index position 0 appears 0 times as shown in array above. Similarly index position 1 appears 5 times and so on. Now we can directly add this 'index_count' array with our vector A. 

In [12]:
print('Required final array is\n\n',value_one_array + index_count)

Required final array is

 [1. 6. 2. 5. 6.]


### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

<font color = blue> A simple and straight forward rephrasing of this question would be:   Find an array using 'np.bincount()' function with 'X' as array argument and 'I' as weights argument. </font>

This is more or less a continuation of the question number 64.

<font color = red>WARNING!!! If you run the code block below the explanation below the code block will be useless as the values will change if you run this code block</font>

In [30]:
X_vector = np.random.randint(1, 10, 10)
print('This is X vector\n\n', X_vector)
I_index = np.random.randint(0, 10, 10)
print('\n\nThis is I index list\n\n', I_index)

F_array = np.bincount(X_vector, I_index)
print('\n\n This is our required F array: \n\n', F_array)

This is X vector

 [3 8 5 4 4 5 4 7 4 6]


This is I index list

 [3 0 5 3 8 7 0 0 8 4]


 This is our required F array: 

 [ 0.  0.  0.  3. 19. 12.  4.  0.  0.]


<font size = 1.2>Interpreting the result:   3 in vector X is accumulated 3 times as given by the index position three in F array. Value 8 is accumulated 0 times indicated in index position eight in F array. 4 is accumulated 19 times. And so on. </font>

<font size = 1.5, color = green>This needs some explanation. We have vector X and index list I. We want to create a new array F where elements of X will be accumulated based on the reference provided by index list I. But the confusing part here is that the accumulated elements are placed at corresponding index position in new array F. For example, consider element 4 in X vector. You can see that 4 is repeated four times in X. Corresponding weight values of 4 in index list I are 3, 8, 0 and 8. Sum of these weights is 3 + 8 + 8 = 19. Clear?  Where does this value appear in new array F? Accumulated weight of value 4 will be placed at index position 4(Remember! count starts from 0 in python). Let us now see for element 3 in vector X. How many 3 are there in X?  Just one. What is the corresponding weight of value 3? It is 3. Where should this weight value go in the new array F? Index position three in F. So, at index position three we have value three. One more example with element 5 in vector X. How many times does it repeat? Twice. What are the corresponding weights of element 5?  5 and 7. Now accumulate(add) all the weights(5,7) of 5 we get 12. Where will this 12 go in new array F?  At index position 5. Can you see value 12 at index position 5 in above array? I guess you can. Perhaps this explanation must me enough to clear how "np.bincount(x, weights)" works. </font>

